// Mocks generated by Mockito 5.4.4 from annotations
// in feed_me/test/provider/feed_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:feed_me/data/models/list_of_restaurant_object_api_response.dart'
    as _i2;
import 'package:feed_me/data/models/object_customer_review_api_response.dart'
    as _i4;
import 'package:feed_me/data/models/object_restaurant_detail_api_response.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

import 'feed_provider_test.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeListOfRestaurantObjectApiResponse_0 extends _i1.SmartFake
    implements _i2.ListOfRestaurantObjectApiResponse {
  _FakeListOfRestaurantObjectApiResponse_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeObjectOfRestaurantDetailApiResponse_1 extends _i1.SmartFake
    implements _i3.ObjectOfRestaurantDetailApiResponse {
  _FakeObjectOfRestaurantDetailApiResponse_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeObjectOfCustomerReviewApiResponse_2 extends _i1.SmartFake
    implements _i4.ObjectOfCustomerReviewApiResponse {
  _FakeObjectOfCustomerReviewApiResponse_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [InterfaceServiceTest].
///
/// See the documentation for Mockito's code generation for more information.
class MockInterfaceServiceTest extends _i1.Mock
    implements _i5.InterfaceServiceTest {
  MockInterfaceServiceTest() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i2.ListOfRestaurantObjectApiResponse> getListOfRestaurant() =>
      (super.noSuchMethod(
        Invocation.method(
          #getListOfRestaurant,
          [],
        ),
        returnValue: _i6.Future<_i2.ListOfRestaurantObjectApiResponse>.value(
            _FakeListOfRestaurantObjectApiResponse_0(
          this,
          Invocation.method(
            #getListOfRestaurant,
            [],
          ),
        )),
      ) as _i6.Future<_i2.ListOfRestaurantObjectApiResponse>);

  @override
  _i6.Future<_i3.ObjectOfRestaurantDetailApiResponse> getRestaurantDetail(
          String? restaurantId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRestaurantDetail,
          [restaurantId],
        ),
        returnValue: _i6.Future<_i3.ObjectOfRestaurantDetailApiResponse>.value(
            _FakeObjectOfRestaurantDetailApiResponse_1(
          this,
          Invocation.method(
            #getRestaurantDetail,
            [restaurantId],
          ),
        )),
      ) as _i6.Future<_i3.ObjectOfRestaurantDetailApiResponse>);

  @override
  _i6.Future<_i2.ListOfRestaurantObjectApiResponse> searchListOfRestaurant(
          String? keyword) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchListOfRestaurant,
          [keyword],
        ),
        returnValue: _i6.Future<_i2.ListOfRestaurantObjectApiResponse>.value(
            _FakeListOfRestaurantObjectApiResponse_0(
          this,
          Invocation.method(
            #searchListOfRestaurant,
            [keyword],
          ),
        )),
      ) as _i6.Future<_i2.ListOfRestaurantObjectApiResponse>);

  @override
  _i6.Future<_i4.ObjectOfCustomerReviewApiResponse> postCustomerReview(
    String? restaurantId,
    String? reviewerName,
    String? reviewComment,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #postCustomerReview,
          [
            restaurantId,
            reviewerName,
            reviewComment,
          ],
        ),
        returnValue: _i6.Future<_i4.ObjectOfCustomerReviewApiResponse>.value(
            _FakeObjectOfCustomerReviewApiResponse_2(
          this,
          Invocation.method(
            #postCustomerReview,
            [
              restaurantId,
              reviewerName,
              reviewComment,
            ],
          ),
        )),
      ) as _i6.Future<_i4.ObjectOfCustomerReviewApiResponse>);
}

/// A class which mocks [ApiServiceTest].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiServiceTest extends _i1.Mock implements _i5.ApiServiceTest {
  MockApiServiceTest() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i2.ListOfRestaurantObjectApiResponse> getListOfRestaurant() =>
      (super.noSuchMethod(
        Invocation.method(
          #getListOfRestaurant,
          [],
        ),
        returnValue: _i6.Future<_i2.ListOfRestaurantObjectApiResponse>.value(
            _FakeListOfRestaurantObjectApiResponse_0(
          this,
          Invocation.method(
            #getListOfRestaurant,
            [],
          ),
        )),
      ) as _i6.Future<_i2.ListOfRestaurantObjectApiResponse>);

  @override
  _i6.Future<_i3.ObjectOfRestaurantDetailApiResponse> getRestaurantDetail(
          String? restaurantId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRestaurantDetail,
          [restaurantId],
        ),
        returnValue: _i6.Future<_i3.ObjectOfRestaurantDetailApiResponse>.value(
            _FakeObjectOfRestaurantDetailApiResponse_1(
          this,
          Invocation.method(
            #getRestaurantDetail,
            [restaurantId],
          ),
        )),
      ) as _i6.Future<_i3.ObjectOfRestaurantDetailApiResponse>);

  @override
  _i6.Future<_i2.ListOfRestaurantObjectApiResponse> searchListOfRestaurant(
          String? keyword) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchListOfRestaurant,
          [keyword],
        ),
        returnValue: _i6.Future<_i2.ListOfRestaurantObjectApiResponse>.value(
            _FakeListOfRestaurantObjectApiResponse_0(
          this,
          Invocation.method(
            #searchListOfRestaurant,
            [keyword],
          ),
        )),
      ) as _i6.Future<_i2.ListOfRestaurantObjectApiResponse>);

  @override
  _i6.Future<_i4.ObjectOfCustomerReviewApiResponse> postCustomerReview(
    String? restaurantId,
    String? name,
    String? comment,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #postCustomerReview,
          [
            restaurantId,
            name,
            comment,
          ],
        ),
        returnValue: _i6.Future<_i4.ObjectOfCustomerReviewApiResponse>.value(
            _FakeObjectOfCustomerReviewApiResponse_2(
          this,
          Invocation.method(
            #postCustomerReview,
            [
              restaurantId,
              name,
              comment,
            ],
          ),
        )),
      ) as _i6.Future<_i4.ObjectOfCustomerReviewApiResponse>);
}
